'use strict';

module.exports = {
	INTERNAL_ERROR: 'INTERNAL_ERROR',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	UNAUTHORIZED: 'UNAUTHORIZED',
	FORBIDDEN: 'FORBIDDEN',
	NOT_FOUND: 'NOT_FOUND',
	CONFLICT_ERROR: 'CONFLICT_ERROR',
	FOREIGN_KEY_ERROR: 'FOREIGN_KEY_ERROR',
	DUPLICATE_ERROR: 'DUPLICATE_ERROR',
	TRANSACTION_ERROR: 'TRANSACTION_ERROR',
};
